;;; packages.el -*- lexical-binding: t; -*-
 (package! cmake-mode :disable t)
 (package! company-irony :disable t)
 (package! company-irony-c-headers :disable t)
 (package! evil-escape :disable t)
 (package! flycheck-irony :disable t)
 (package! irony :disable t)
 (package! irony-eldoc :disable t)
 (package! ivy-rtags :disable t)
 (package! rtags :disable t)
